export const codeLanguages = [
  { name: "abap", label: "ABAP" },
  { name: "abnf", label: "Augmented Backus–Naur form" },
  { name: "actionscript", label: "ActionScript" },
  { name: "ada", label: "Ada" },
  { name: "antlr4", label: "ANTLR4" },
  { name: "g4", label: "ANTLR4" },
  { name: "apacheconf", label: "Apache Configuration" },
  { name: "apl", label: "APL" },
  { name: "applescript", label: "AppleScript" },
  { name: "aql", label: "AQL" },
  { name: "arduino", label: "Arduino" },
  { name: "arff", label: "ARFF" },
  { name: "asciidoc", label: "AsciiDoc" },
  { name: "adoc", label: "AsciiDoc" },
  { name: "asm6502", label: "6502 Assembly" },
  { name: "aspnet", label: "ASP.NET (C#)" },
  { name: "autohotkey", label: "AutoHotkey" },
  { name: "autoit", label: "AutoIt" },
  { name: "bash", label: "Bash" },
  { name: "shell", label: "Bash" },
  { name: "basic", label: "BASIC" },
  { name: "batch", label: "Batch" },
  { name: "bbcode", label: "BBcode" },
  { name: "shortcode", label: "BBcode" },
  { name: "bison", label: "Bison" },
  { name: "bnf", label: "Backus–Naur form" },
  { name: "rbnf", label: "Backus–Naur form" },
  { name: "brainfuck", label: "Brainfuck" },
  { name: "brightscript", label: "BrightScript" },
  { name: "bro", label: "Bro" },
  { name: "c", label: "C" },
  { name: "cil", label: "CIL" },
  { name: "clike", label: "C-like" },
  { name: "clojure", label: "Clojure" },
  { name: "cmake", label: "CMake" },
  { name: "coffeescript", label: "CoffeeScript" },
  { name: "coffee", label: "CoffeeScript" },
  { name: "concurnas", label: "Concurnas" },
  { name: "conc", label: "Concurnas" },
  { name: "cpp", label: "C++" },
  { name: "crystal", label: "Crystal" },
  { name: "csharp", label: "C#" },
  { name: "cs", label: "C#" },
  { name: "dotnet", label: "C#" },
  { name: "csp", label: "Content-Security-Policy" },
  { name: "css", label: "CSS" },
  { name: "css-extras", label: "CSS Extras" },
  { name: "d", label: "D" },
  { name: "dart", label: "Dart" },
  { name: "dax", label: "DAX" },
  { name: "diff", label: "Diff" },
  { name: "django", label: "Django/Jinja2" },
  { name: "jinja2", label: "Django/Jinja2" },
  { name: "dns-zone-file", label: "DNS zone file" },
  { name: "dns-zone", label: "DNS zone file" },
  { name: "docker", label: "Docker" },
  { name: "dockerfile", label: "Docker" },
  { name: "ebnf", label: "Extended Backus–Naur form" },
  { name: "eiffel", label: "Eiffel" },
  { name: "ejs", label: "EJS" },
  { name: "elixir", label: "Elixir" },
  { name: "elm", label: "Elm" },
  { name: "erb", label: "ERB" },
  { name: "erlang", label: "Erlang" },
  { name: "etlua", label: "Embedded Lua templating" },
  { name: "excel-formula", label: "Excel Formula" },
  { name: "xlsx", label: "Excel Formula" },
  { name: "xls", label: "Excel Formula" },
  { name: "factor", label: "Factor" },
  { name: "firestore-security-rules", label: "Firestore security rules" },
  { name: "flow", label: "Flow" },
  { name: "fortran", label: "Fortran" },
  { name: "fsharp", label: "F#" },
  { name: "ftl", label: "FreeMarker Template Language" },
  { name: "gcode", label: "G-code" },
  { name: "gdscript", label: "GDScript" },
  { name: "gherkin", label: "Gherkin" },
  { name: "git", label: "Git" },
  { name: "glsl", label: "GLSL" },
  { name: "gml", label: "GameMaker Language" },
  { name: "gamemakerlanguage", label: "GameMaker Language" },
  { name: "go", label: "Go" },
  { name: "graphql", label: "GraphQL" },
  { name: "groovy", label: "Groovy" },
  { name: "haml", label: "Haml" },
  { name: "handlebars", label: "Handlebars" },
  { name: "haskell", label: "Haskell" },
  { name: "hs", label: "Haskell" },
  { name: "haxe", label: "Haxe" },
  { name: "hcl", label: "HCL" },
  { name: "hpkp", label: "HTTP Public-Key-Pins" },
  { name: "hsts", label: "HTTP Strict-Transport-Security" },
  { name: "http", label: "HTTP" },
  { name: "ichigojam", label: "IchigoJam" },
  { name: "icon", label: "Icon" },
  { name: "inform7", label: "Inform 7" },
  { name: "ini", label: "Ini" },
  { name: "io", label: "Io" },
  { name: "j", label: "J" },
  { name: "java", label: "Java" },
  { name: "javadoc", label: "JavaDoc" },
  { name: "javadoclike", label: "JavaDoc-like" },
  { name: "javascript", label: "JavaScript" },
  { name: "js", label: "JavaScript" },
  { name: "javastacktrace", label: "Java stack trace" },
  { name: "jolie", label: "Jolie" },
  { name: "jq", label: "JQ" },
  { name: "js-extras", label: "JS Extras" },
  { name: "js-templates", label: "JS Templates" },
  { name: "jsdoc", label: "JSDoc" },
  { name: "json", label: "JSON" },
  { name: "json5", label: "JSON5" },
  { name: "jsonp", label: "JSONP" },
  { name: "jsx", label: "React JSX" },
  { name: "julia", label: "Julia" },
  { name: "keyman", label: "Keyman" },
  { name: "kotlin", label: "Kotlin" },
  { name: "latex", label: "LaTeX" },
  { name: "tex", label: "LaTeX" },
  { name: "context", label: "LaTeX" },
  { name: "latte", label: "Latte" },
  { name: "less", label: "Less" },
  { name: "lilypond", label: "LilyPond" },
  { name: "ly", label: "LilyPond" },
  { name: "liquid", label: "Liquid" },
  { name: "lisp", label: "Lisp" },
  { name: "emacs", label: "Lisp" },
  { name: "elisp", label: "Lisp" },
  { name: "emacs-lisp", label: "Lisp" },
  { name: "livescript", label: "LiveScript" },
  { name: "llvm", label: "LLVM IR" },
  { name: "lolcode", label: "LOLCODE" },
  { name: "lua", label: "Lua" },
  { name: "makefile", label: "Makefile" },
  { name: "markdown", label: "Markdown" },
  { name: "md", label: "Markdown" },
  { name: "markup", label: "Markup" },
  { name: "html", label: "Markup" },
  { name: "xml", label: "Markup" },
  { name: "svg", label: "Markup" },
  { name: "mathml", label: "Markup" },
  { name: "markup-templating", label: "Markup templating" },
  { name: "matlab", label: "MATLAB" },
  { name: "mel", label: "MEL" },
  { name: "meta", label: "NO_TITLE" },
  { name: "mizar", label: "Mizar" },
  { name: "monkey", label: "Monkey" },
  { name: "moonscript", label: "MoonScript" },
  { name: "moon", label: "MoonScript" },
  { name: "n1ql", label: "N1QL" },
  { name: "n4js", label: "N4JS" },
  { name: "n4jsd", label: "N4JS" },
  { name: "nand2tetris-hdl", label: "Nand To Tetris HDL" },
  { name: "nasm", label: "NASM" },
  { name: "neon", label: "NEON" },
  { name: "nginx", label: "nginx" },
  { name: "nim", label: "Nim" },
  { name: "nix", label: "Nix" },
  { name: "nsis", label: "NSIS" },
  { name: "objectivec", label: "Objective-C" },
  { name: "ocaml", label: "OCaml" },
  { name: "opencl", label: "OpenCL" },
  { name: "oz", label: "Oz" },
  { name: "parigp", label: "PARI/GP" },
  { name: "parser", label: "Parser" },
  { name: "pascal", label: "Pascal" },
  { name: "objectpascal", label: "Pascal" },
  { name: "pascaligo", label: "Pascaligo" },
  { name: "pcaxis", label: "PC-Axis" },
  { name: "px", label: "PC-Axis" },
  { name: "perl", label: "Perl" },
  { name: "php", label: "PHP" },
  { name: "php-extras", label: "PHP Extras" },
  { name: "phpdoc", label: "PHPDoc" },
  { name: "plsql", label: "PL/SQL" },
  { name: "powerquery", label: "PowerQuery" },
  { name: "pq", label: "PowerQuery" },
  { name: "mscript", label: "PowerQuery" },
  { name: "powershell", label: "PowerShell" },
  { name: "processing", label: "Processing" },
  { name: "prolog", label: "Prolog" },
  { name: "properties", label: ".properties" },
  { name: "protobuf", label: "Protocol Buffers" },
  { name: "pug", label: "Pug" },
  { name: "puppet", label: "Puppet" },
  { name: "pure", label: "Pure" },
  { name: "python", label: "Python" },
  { name: "py", label: "Python" },
  { name: "q", label: "Q (kdb+ database)" },
  { name: "qml", label: "QML" },
  { name: "qore", label: "Qore" },
  { name: "r", label: "R" },
  { name: "reason", label: "Reason" },
  { name: "regex", label: "Regex" },
  { name: "renpy", label: "Ren'py" },
  { name: "rest", label: "reST (reStructuredText)" },
  { name: "rip", label: "Rip" },
  { name: "roboconf", label: "Roboconf" },
  { name: "robotframework", label: "Robot Framework" },
  { name: "robot", label: "Robot Framework" },
  { name: "ruby", label: "Ruby" },
  { name: "rb", label: "Ruby" },
  { name: "rust", label: "Rust" },
  { name: "sas", label: "SAS" },
  { name: "sass", label: "Sass (Sass)" },
  { name: "scss", label: "Sass (Scss)" },
  { name: "scheme", label: "Scheme" },
  { name: "shell-session", label: "Shell session" },
  { name: "smalltalk", label: "Smalltalk" },
  { name: "smarty", label: "Smarty" },
  { name: "solidity", label: "Solidity (Ethereum)" },
  { name: "solution-file", label: "Solution file" },
  { name: "sln", label: "Solution file" },
  { name: "soy", label: "Soy (Closure Template)" },
  { name: "sparql", label: "SPARQL" },
  { name: "rq", label: "SPARQL" },
  { name: "splunk-spl", label: "Splunk SPL" },
  { name: "sqf", label: "SQF: Status Quo Function (Arma 3)" },
  { name: "sql", label: "SQL" },
  { name: "stylus", label: "Stylus" },
  { name: "swift", label: "Swift" },
  { name: "t4-cs", label: "T4 Text Templates (C#)" },
  { name: "t4", label: "T4 Text Templates (C#)" },
  { name: "t4-templating", label: "T4 templating" },
  { name: "t4-vb", label: "T4 Text Templates (VB)" },
  { name: "tap", label: "TAP" },
  { name: "tcl", label: "Tcl" },
  { name: "textile", label: "Textile" },
  { name: "toml", label: "TOML" },
  { name: "tsx", label: "React TSX" },
  { name: "tt2", label: "Template Toolkit 2" },
  { name: "turtle", label: "Turtle" },
  { name: "trig", label: "Turtle" },
  { name: "twig", label: "Twig" },
  { name: "typescript", label: "TypeScript" },
  { name: "ts", label: "TypeScript" },
  { name: "vala", label: "Vala" },
  { name: "vbnet", label: "VB.Net" },
  { name: "velocity", label: "Velocity" },
  { name: "verilog", label: "Verilog" },
  { name: "vhdl", label: "VHDL" },
  { name: "vim", label: "vim" },
  { name: "visual-basic", label: "Visual Basic" },
  { name: "vb", label: "Visual Basic" },
  { name: "wasm", label: "WebAssembly" },
  { name: "wiki", label: "Wiki markup" },
  { name: "xeora", label: "Xeora" },
  { name: "xeoracube", label: "Xeora" },
  { name: "xojo", label: "Xojo (REALbasic)" },
  { name: "xquery", label: "XQuery" },
  { name: "yaml", label: "YAML" },
  { name: "yml", label: "YAML" },
  { name: "zig", label: "Zig" }
]

export const codeLanguagesMap = new Map(codeLanguages.map(c => [c.name, c.label]));

export const sortedCodeLanguages = (recentCodeLanguages: string[]) =>
{
    const keys = [...recentCodeLanguages, ...codeLanguagesMap.keys()];
    return [...new Set(keys).values()].map(k => ({ name: k, label: codeLanguagesMap.get(k) ?? k}));
}
