export const TokenTypes = new Map<string, [string, string]>([
    ['', ['選択無し', '']],
    ['heading', ['ヘディング', 'Hed']],
    ['table', ['テーブル', 'TBL']],
    ['tableRow', ['テーブル行', 'ROW']],
    ['tableCell', ['テーブルセル', 'CEL']],
    ['paragraph', ['段落', 'P']],
    ['text', ['テキスト', 'Tx']],
    ['emphasis', ['イタリック', 'It']],
    ['strong', ['太字', 'B']],
    ['delete', ['取り消し線', 'S']],
    ['break', ['改行', 'Br']],
    ['list', ['リスト', 'Lst']],
    ['listItem', ['リストアイテム', 'Li']],
    ['blockquote', ['引用', 'Nt']],
    ['code', ['コード', 'Cd']],
    ['inlineCode', ['インラインコード', 'Ic']],
    ['link', ['リンク', 'Lin']],
    ['image', ['画像', 'Img']],
    ['thematicBreak', ['水平線', 'Hr']],
    ['html', ['HTML', 'Htm']],
    ['linkReference', ['リンク参照', 'Ref']],
    ['definition', ['定義', 'Def']]
])
